language: node_js
node_js:
  - '8'
  - '10'
  - '12'
branches:
  - master
stages:
  - test 
before_script:
  - npm ci
script:
  - npm uninstall typescript --no-save
  - npm install
  - npm install --save-dev jest
  - npm i @types/jest
  - npm test